version: "2.1"
services:
  parchapp-pdfevento-ms:
    build: .
    ports:
      - "5004:5004"
    depends_on:
      parchapp-pdfevento-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I parchapp-pdfevento-ms:5004/parchapp-pdfevento-ms/resources/events/ --fail"
      interval: 20s
      retries: 10
  parchapp-pdfevento-db:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: pdfevento
      MYSQL_USER: parchapp
      MYSQL_PASSWORD: 2019ii
    ports:
      - "32004:3306"